language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - npm prune
  - greenkeeper-lockfile-update
script:
  - npm run lint
  - npm run test
after_script: greenkeeper-lockfile-upload
branches:
  only:
    - master
    - /^greenkeeper/.*$/
